name: General Developer Action
description: Setup your runner with Flutter environment
author: General Developer
branding:
  icon: maximize
  color: blue

inputs:
  channel:
    description: The Flutter build release channel
    required: false
    default: stable
  flutter-version:
    description: The Flutter version to make available on the path
    required: false
    default: ""
  flutter-version-file:
    description: The pubspec.yaml file with exact Flutter version defined
    required: false
    default: ""
  architecture:
    description: The architecture of Flutter SDK executable (x64 or arm64)
    required: false
    default: "${{ runner.arch }}"
  cache:
    description: Cache the Flutter SDK
    required: false
    default: "false"
  cache-key:
    description: Identifier for the Flutter SDK cache
    required: false
    default: ""
  cache-path:
    description: Flutter SDK cache path
    required: false
    default: ""
  pub-cache-key:
    description: Identifier for the Dart .pub-cache cache
    required: false
    default: ""
  pub-cache-path:
    description: Flutter pub cache path
    required: false
    default: default
  dry-run:
    description: If true, get outputs but do not install Flutter
    required: false
    default: "false"
  git-source:
    description: Git clone source
    required: false
    default: "https://github.com/flutter/flutter.git"

# outputs:
#   CHANNEL:
#     value: "${{ inputs.CHANNEL }}"
#     description: The selected Flutter release channel
#   VERSION:
#     value: "${{ inputs.VERSION }}"
#     description: The selected Flutter version
#   ARCHITECTURE:
#     value: "${{ inputs.ARCHITECTURE }}"
#     description: The selected Flutter CPU architecture
#   cache-key:
#     value: "${{ inputs.cache-key }}"
#     description: Key used to cache the Flutter SDK
#   cache-path:
#     value: "${{ inputs.cache-path }}"
#     description: Path to Flutter SDK
#   pub-cache-key:
#     value: "${{ inputs.pub-cache-key }}"
#     description: Key used to cache the pub dependencies
#   pub-cache-path:
#     value: "${{ inputs.pub-cache-path }}"
#     description: Path to pub cache
#   GIT_SOURCE:
#     value: "${{ inputs.GIT_SOURCE }}"
#     description: Git source of Flutter SDK repository to clone

runs:
  using: composite
  steps:
    # This is a cross-platform composite action that needs yq.
    # It's not preinstalled on Windows runners.
    # See https://github.com/actions/runner-images/issues/7443#issuecomment-1514597691
    - name: Make yq tool available on Windows runners
      if: runner.os == 'Windows'
      run: choco install yq
      shell: bash

    - name: Make setup script executable
      run: chmod +x "$GITHUB_ACTION_PATH/setup.sh"
      shell: bash

    - name: Set action inputs
      id: general-developer-action
      shell: bash
      run: |
        $GITHUB_ACTION_PATH/setup.sh -p \
          -n '${{ inputs.flutter-version }}' \
          -f '${{ inputs.flutter-version-file }}' \
          -a '${{ inputs.architecture }}' \
          -k '${{ inputs.cache-key }}' \
          -c '${{ inputs.cache-path }}' \
          -l '${{ inputs.pub-cache-key }}' \
          -d '${{ inputs.pub-cache-path }}' \
          -g '${{ inputs.git-source }}' \
          ${{ inputs.channel }}

    - name: Cache Flutter
      uses: actions/cache@v4
      if: ${{ inputs.cache == 'true' }}
      with:
        path: ${{ inputs.cache-path }}
        key: ${{ inputs.cache-key }}
        restore-keys: |
          ${{ inputs.cache-key }}

    - name: Cache pub dependencies
      uses: actions/cache@v4
      if: ${{ inputs.cache == 'true' }}
      with:
        path: ${{ inputs.pub-cache-path }}
        key: ${{ inputs.pub-cache-key }}-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          ${{ inputs.pub-cache-key }}-${{ hashFiles('**/pubspec.lock') }}
          ${{ inputs.pub-cache-key }}

    - name: Run setup script
      shell: bash
      if: ${{ inputs.dry-run != 'true' && inputs.dry-run != true }}
      run: |
        $GITHUB_ACTION_PATH/setup.sh \
          -n '${{ inputs.VERSION }}' \
          -a '${{ inputs.ARCHITECTURE }}' \
          -c '${{ inputs.cache-path }}' \
          ${{ inputs.CHANNEL }}
