name: General Developer Action
description: Setup your runner with Flutter environment
author: General Developer
branding:
  icon: maximize
  color: blue

inputs:
  architecture:
    description: The architecture of Flutter SDK executable (x64 or arm64)
    required: false
    default: "${{ runner.arch }}"
  is_use_cache:
    description: Cache the Flutter SDK
    required: false
    default: "true"
  flutter_channel:
    description: The Flutter build release channel
    required: false
    default: "stable"
  flutter_version:
    description: The Flutter version to make available on the path
    required: false
    default: "3.29.0"
  flutter_version_file:
    description: The pubspec.yaml file with exact Flutter version defined
    required: false
    default: ""
  flutter_cache_key:
    description: Identifier for the Flutter SDK cache
    required: false
    default: "flutter-sdk-cache-${{ runner.os }}"
  flutter_pub_cache_key:
    description: Identifier for the Flutter SDK cache
    required: false
    default: "flutter-pub-sdk-cache-${{ runner.os }}"
  flutter_git_url:
    description: Git clone source
    required: false
    default: "https://github.com/flutter/flutter.git"
 

runs:
  using: composite
  steps:
    # This is a cross-platform composite action that needs yq.
    # It's not preinstalled on Windows runners.
    # See https://github.com/actions/runner-images/issues/7443#issuecomment-1514597691
    - name: Make yq tool available on Windows runners
      if: runner.os == 'Windows'
      shell: bash
      run: choco install yq

    - name: Make setup script executable
      shell: bash
      run: chmod +x "$GITHUB_ACTION_PATH/setup.sh"

    - name: Set action inputs
      id: general-developer-action
      shell: bash
      run: |
        $GITHUB_ACTION_PATH/setup.sh -p \
          -n '${{ inputs.flutter_version }}' \
          -f '${{ inputs.flutter_version_file }}' \
          -a '${{ inputs.architecture }}' \
          -k '${{ inputs.flutter_cache_key }}' \
          -c '${{ inputs.flutter_cache_key }}' \
          -l '${{ inputs.flutter_pub_cache_key }}' \
          -d '${{ inputs.flutter_pub_cache_key }}' \
          -g '${{ inputs.flutter_git_url }}' \
          ${{ inputs.flutter_channel }}

    - name: Cache Flutter
      uses: actions/cache@v4.2.2
      if: ${{ inputs.is_use_cache == 'true' }}
      with:
        path: ${{ inputs.flutter_cache_key }}
        key: ${{ inputs.flutter_cache_key }}
        restore-keys: |
          ${{ inputs.flutter_cache_key }}

    - name: Cache pub dependencies
      uses: actions/cache@v4.2.2
      if: ${{ inputs.is_use_cache == 'true' }}
      with:
        path: ${{ inputs.flutter_pub_cache_key }}
        key: ${{ inputs.flutter_pub_cache_key }}
        restore-keys: |
          ${{ inputs.flutter_pub_cache_key }}

    - name: Run setup script
      shell: bash
      run: |
        $GITHUB_ACTION_PATH/setup.sh \
          -n '${{ inputs.flutter_version }}' \
          -a '${{ inputs.architecture }}' \
          -c '${{ inputs.flutter_cache_key }}' \
          ${{ inputs.flutter_channel }}