name: 'general_developer_action'
description: 'A sample command-line application.'
version: '1.0.0'
environment:
  sdk: '>=3.6.0 <4.0.0'
dependencies: {}
dev_dependencies:
  lints: '^5.0.0'
  test: 'any'
project:
  type: ''
dependency_overrides:
  pointycastle: '3.8.0'
  mime: '^2.0.0'
funding: []
