name: General Testing
on: 
  workflow_dispatch: 
jobs: 
  general-action-test:
    name: General Action Test
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          # check done
          - os: macos-latest # build macos  
          - os: ubuntu-24.04 # build android 
          - os: windows-latest # build windows 
    runs-on: ${{ matrix.os }}
    steps:  
    

      - name: General Developer Action
        uses: General-Developer/general-developer-action@0.0.5
  
      - name: Flutter Version
        shell: bash
        run: |
          mkdir -p another-work

      - name: Flutter Version
        working-directory: another-work
        run: |
          flutter --version