name: General Testing
on: 
  workflow_dispatch: 
jobs: 
  general-action-test:
    name: General Action Test
    timeout-minutes: 30
    strategy:
      # fail-fast: true
      matrix:
        include:
          # check done
          - os: macos-latest # build macos  
          - os: ubuntu-24.04 # build android 
          - os: windows-latest # build windows 
    runs-on: ${{ matrix.os }}
    steps:  
    

      - name: General Developer Action
        uses: General-Developer/general-developer-action@0.0.6
        with:
          flutter_channel: stable
          flutter_version: 3.29.0
          is_use_cache: true
          flutter_cache_key: "flutter-path-${{ runner.os }}-3.29.0"

      - name: Flutter Version
        shell: bash
        run: |
          mkdir -p another-work

      - name: Flutter Version
        working-directory: another-work
        run: |
          flutter --version