name: Testing
on: 
  workflow_dispatch:
jobs: 
  general-developer-action-test:
    name: General Developer Action Test
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          # check done
          - os: macos-latest # build macos  
          - os: ubuntu-24.04 # build android 
          - os: windows-latest # build windows 
    runs-on: ${{ matrix.os }}
    steps:  

      - uses: actions/checkout@v4
        with:
         fetch-depth: 1
         path: general-developer-action

      - name: General Developer Action
        uses: ./general-developer-action
      # - name: General Developer Action
        # uses: General-Developer/general-developer-action@latest
        # with:
        #   channel: stable
        #   flutter-version: 3.29.0
        #   cache: true
        #   # cache-key: "flutter-cache-${{ runner.os }}-3.29.0"
        #   # cache-path: "flutter-path-${{ runner.os }}-3.29.0"
        #   # pub-cache-key: "flutter-pub-cache-${{ runner.os }}-3.29.0"
        #   # pub-cache-path: "flutter-pub-path-${{ runner.os }}-3.29.0"

        